# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wealthify
spring.datasource.username=expense_user
spring.datasource.password=expense123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=mySecretKey123456789012345678901234567890
app.jwt.expiration=86400000

# App
spring.application.name=Wealthify

# Groq AI
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
groq.api.key=REPLACE_WITH_YOUR_GROQ_KEY